[package]
name = "cargo-nav"
version = "0.1.0"
authors = ["Celeo <mattboulanger@fastmail.com>"]
edition = "2018"
description = "Navigate directly to crate links"
readme = "README.md"
homepage = "https://github.com/celeo/roles_for_reactions"
repository = "https://github.com/celeo/roles_for_reactions"
license = "MIT OR Apache-2.0"
exclude = [
  ".github",
  "licenses"
]

[dependencies]
anyhow = "1.0.31"
fern = "0.6.0"
log = "0.4.8"
reqwest = { version = "0.10.6", features = ["blocking", "json"] }
serde = { version = "1.0.113", features = ["derive"]}
serde_json = "1.0.55"
structopt = "0.3.15"
